// This file will be auto-generated by `pnpm db:types`
// After the first Supabase project is set up, run:
// NEXT_PUBLIC_SUPABASE_PROJECT_ID=your-project-id pnpm db:types

export type Database = {
  public: {
    Tables: Record<string, unknown>;
    Views: Record<string, unknown>;
    Functions: Record<string, unknown>;
    Enums: Record<string, unknown>;
    CompositeTypes: Record<string, unknown>;
  };
};
