// NEXT_PUBLIC_APP_URL for local dev (pure: no fs, no process spawning).
//
// The app's own mail (sendTeamMail, src/features/mail/send.ts) builds its
// `/auth/confirm?token_hash=…` button from NEXT_PUBLIC_APP_URL. Locally that
// token is minted by the LOCAL Supabase stack, so a button pointing at the prod
// origin can never be verified: the invite link "never works". dev-env.mjs
// therefore writes the key for the port it serves on, and corrects a stale
// localhost port at serve time (each worktree claims its own 70xx port, CI and
// Playwright pin 3000).

export const APP_URL_KEY = 'NEXT_PUBLIC_APP_URL';

export function localAppUrl(port) {
  return `http://localhost:${port}`;
}

/** The .env.local that dev-env.mjs writes when none exists. */
export function envLocalBody({ url, anon, service, port }) {
  return (
    [
      '# Auto-generated by scripts/dev-env.mjs for LOCAL dev against the shared Supabase stack.',
      '# Local-only and gitignored. Delete it to regenerate, or replace it to point elsewhere.',
      `NEXT_PUBLIC_SUPABASE_URL=${url}`,
      `NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}`,
      `SUPABASE_SERVICE_ROLE_KEY=${service}`,
      // Origin of the links in the app's own mail (invites). `pnpm dev` keeps the
      // port in step with the one it serves on; a non-localhost value is left alone.
      `${APP_URL_KEY}=${localAppUrl(port)}`,
    ].join('\n') + '\n'
  );
}

/** Value of `key` in dotenv text (quotes stripped), or null when absent/empty. */
export function readEnvValue(text, key) {
  const m = text.match(new RegExp(`^\\s*${key}\\s*=\\s*"?([^"\\r\\n]*)"?\\s*$`, 'm'));
  const value = m ? m[1].trim() : '';
  return value || null;
}

function isLocalHost(value) {
  try {
    const { hostname } = new URL(value);
    return hostname === 'localhost' || hostname === '127.0.0.1';
  } catch {
    return false;
  }
}

/**
 * What to do about NEXT_PUBLIC_APP_URL for an EXISTING .env.local (which
 * dev-env.mjs never rewrites):
 *  - `hint`: a line to print when the key is missing from a file that points at
 *    the local stack (the app falls back to http://localhost:$PORT in dev, but
 *    scripts like invite-link.mjs read the file).
 *  - `override`: the value to hand `next dev` when the file holds a localhost
 *    origin on another port. A process env var wins over .env.local in Next,
 *    and a localhost origin on the wrong port is never what this server wants.
 *    Any non-localhost value (a tunnel, a deliberate prod origin) is kept.
 */
export function appUrlAdvice(envText, port) {
  const want = localAppUrl(port);
  const current = readEnvValue(envText, APP_URL_KEY);
  if (current === null) {
    const supabaseUrl = readEnvValue(envText, 'NEXT_PUBLIC_SUPABASE_URL') ?? '';
    if (!isLocalHost(supabaseUrl)) return {};
    return {
      hint:
        `[dev-env] .env.local has no ${APP_URL_KEY}. Invite mail falls back to ${want} in dev; ` +
        `add \`${APP_URL_KEY}=${want}\` to .env.local to make it explicit (scripts read it too).`,
    };
  }
  if (!isLocalHost(current)) return {};
  if (current.replace(/\/+$/, '') === want) return {};
  return {
    override: want,
    note: `[dev-env] ${APP_URL_KEY} in .env.local is ${current}; serving on ${want}, so this run uses ${want}.`,
  };
}
