// Auto-provision .env.local for LOCAL development.
//
// Every git worktree is a separate checkout with its own node_modules and its own
// dev server, but they all share ONE local Supabase stack (fixed 553xx ports,
// keyed by supabase/config.toml). The only thing a fresh worktree was missing to
// "just work" was .env.local — so `pnpm dev` runs this first to write it from the
// running stack. Result: a new session only ever rebuilds CODE, never the env.
//
// Rules:
//   - If .env.local already exists, do nothing (respect an explicit/prod env —
//     e.g. the main checkout that points at prod for `supabase db push`).
//   - Otherwise read the live keys from `supabase status -o env` and remap them
//     to the plain NEXT_PUBLIC_* names the app uses.
//   - NEVER block `next dev`: any problem just prints guidance and exits 0.
import { existsSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { resolve } from 'node:path';

const envPath = resolve(process.cwd(), '.env.local');

function main() {
  if (existsSync(envPath)) return; // respect an existing env file

  let raw;
  try {
    raw = execSync('supabase status -o env', { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
  } catch {
    console.warn(
      '\n[dev-env] No running local Supabase stack found.\n' +
        '          Start the shared stack once with `pnpm supabase:start`, then re-run `pnpm dev`.\n'
    );
    return;
  }

  const get = (key) => {
    const m = raw.match(new RegExp(`^${key}="?([^"\\n]+)"?`, 'm'));
    return m ? m[1] : '';
  };
  const url = get('API_URL');
  const anon = get('ANON_KEY');
  const service = get('SERVICE_ROLE_KEY');
  if (!url || !anon) {
    console.warn('[dev-env] Could not parse `supabase status -o env`; skipping .env.local generation.');
    return;
  }

  const body =
    [
      '# Auto-generated by scripts/dev-env.mjs for LOCAL dev against the shared Supabase stack.',
      '# Local-only and gitignored. Delete it to regenerate, or replace it to point elsewhere.',
      `NEXT_PUBLIC_SUPABASE_URL=${url}`,
      `NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}`,
      `SUPABASE_SERVICE_ROLE_KEY=${service}`,
    ].join('\n') + '\n';

  writeFileSync(envPath, body, 'utf8');
  console.log(`[dev-env] Wrote .env.local -> ${url} (shared local Supabase).`);
}

try {
  main();
} catch (e) {
  console.warn('[dev-env] Unexpected error; continuing without writing .env.local:', e?.message ?? e);
}
process.exit(0);
