#!/usr/bin/env node
/**
 * Regenerates every app icon, splash and PWA icon from the vector master
 * `native/icon/plusone-mark.svg` (86ey6bft8). Run from the repo root:
 *
 *   node scripts/native-icons.mjs
 *
 * One geometry rule everywhere: the "+1" is centred on its ink bounding box
 * and its height is MARK_HEIGHT (36%) of the visible tile (the full square,
 * the 72dp visible part of the 108dp adaptive canvas, or the 160dp splash
 * circle). Outputs are deterministic; commit whatever changes.
 *
 * Writes:
 *  - native/icon/plusone-icon.svg            mark on the lavender tile (derived)
 *  - Android  adaptive icon (vector foreground/monochrome on a colour background),
 *             legacy mipmaps (pre-26), splash drawables (API 31+ and pre-31)
 *  - iOS      AppIcon.appiconset (every size, opaque), Splash.imageset (the
 *             lavender circle the LaunchScreen storyboard centres)
 *  - public/  icon-*.png, icon-maskable-*.png, apple-touch-icon.png
 *  - src/app/ favicon.ico (16/32/48) + icon.svg: the browser-tab icon via the
 *             Next file-based metadata convention (apple-touch-icon stays the
 *             explicit <link> in src/app/layout.tsx; no src/app/apple-icon.*)
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const at = (...p) => join(root, ...p);

const LAVENDER = '#B5A6FF'; // design-system accent: icon tile / splash circle
const NEAR_BLACK = '#0B0B0D'; // design-system background: splash screen
const MARK_HEIGHT = 0.36;

// --- the master ------------------------------------------------------------
const markSvg = readFileSync(at('native/icon/plusone-mark.svg'), 'utf8');
const [, vbW, vbH] = markSvg.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/).map(Number);
const pathD = markSvg.match(/<path[^>]*\sd="([^"]+)"/)[1];
const ink = markSvg.match(/<path[^>]*fill="(#[0-9A-Fa-f]{6})"/)[1];

/** Transform placing the mark centred in a `box` square, height = `height` * visible. */
function place(box, visible = box, height = MARK_HEIGHT) {
  const r = (n) => Math.round(n * 1e6) / 1e6;
  const s = r((height * visible) / vbH);
  return { s, x: r((box - vbW * s) / 2), y: r((box - vbH * s) / 2) };
}

/** Square SVG: optional tile (full / rounded / circle), the mark centred on top. */
function svg(size, { tile = null, circle = false, radius = 0, height = MARK_HEIGHT, visible = size } = {}) {
  const { s, x, y } = place(size, visible, height);
  const bg = !tile
    ? ''
    : circle
      ? `<circle cx="${size / 2}" cy="${size / 2}" r="${size / 2}" fill="${tile}"/>`
      : `<rect width="${size}" height="${size}"${radius ? ` rx="${radius * size}"` : ''} fill="${tile}"/>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">${bg}<path transform="translate(${x} ${y}) scale(${s})" fill="${ink}" d="${pathD}"/></svg>`;
}

async function png(file, size, opts, { opaque = false } = {}) {
  mkdirSync(dirname(at(file)), { recursive: true });
  let img = sharp(Buffer.from(svg(1024, opts)), { density: 72 }).resize(size, size);
  if (opaque) img = img.flatten({ background: opts.tile ?? NEAR_BLACK }).removeAlpha();
  await img.png({ compressionLevel: 9 }).toFile(at(file));
}

function write(file, text) {
  mkdirSync(dirname(at(file)), { recursive: true });
  writeFileSync(at(file), text);
}

const GENERATED = 'Generated by scripts/native-icons.mjs from native/icon/plusone-mark.svg; do not edit by hand.';

/** Android VectorDrawable of the mark on a `canvas`dp square, sized for `visible`dp. */
function vector(canvas, visible, extra = '') {
  const { s, x, y } = place(canvas, visible);
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GENERATED} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${canvas}dp"
    android:height="${canvas}dp"
    android:viewportWidth="${canvas}"
    android:viewportHeight="${canvas}">
${extra}    <group
        android:translateX="${x}"
        android:translateY="${y}"
        android:scaleX="${s}"
        android:scaleY="${s}">
        <path
            android:fillColor="${ink}"
            android:pathData="${pathD}" />
    </group>
</vector>
`;
}

// --- derived vector source ---------------------------------------------------
write(
  'native/icon/plusone-icon.svg',
  `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${GENERATED} The "+1" mark on the lavender tile, ${MARK_HEIGHT * 100}% glyph height, ink-centred. -->
${svg(1024, { tile: LAVENDER })}
`,
);

// --- Android -----------------------------------------------------------------
const res = 'android/app/src/main/res';

// Adaptive icon (API 26+): 108dp canvas, 72dp visible after the launcher mask,
// 66dp safe zone. Foreground = the mark on transparent; background = a colour.
write(`${res}/drawable/ic_launcher_foreground.xml`, vector(108, 72));
const adaptive = `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GENERATED} -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
`;
write(`${res}/mipmap-anydpi-v26/ic_launcher.xml`, adaptive);
write(`${res}/mipmap-anydpi-v26/ic_launcher_round.xml`, adaptive);

// Legacy launcher icons (pre-26): the full tile / the tile as a circle.
const DENSITIES = { ldpi: 0.75, mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 };
for (const [d, k] of Object.entries(DENSITIES)) {
  const px = Math.round(48 * k);
  await png(`${res}/mipmap-${d}/ic_launcher.png`, px, { tile: LAVENDER });
  await png(`${res}/mipmap-${d}/ic_launcher_round.png`, px, { tile: LAVENDER, circle: true });
}

// Splash. Android 12+ draws windowSplashScreenAnimatedIcon at 240dp with the
// icon-background colour in the inner 160dp circle, so the v31 icon is the mark
// alone. core-splashscreen on API < 31 paints that "icon background" in the
// splash BACKGROUND colour instead, so the base icon carries its own circle.
const circle160 = `    <path
        android:fillColor="${LAVENDER}"
        android:pathData="M120,40a80,80 0,1 1,0 160a80,80 0,1 1,0 -160z" />
`;
write(`${res}/drawable/splash_mark.xml`, vector(240, 160));
write(`${res}/drawable-v31/splash_icon.xml`, vector(240, 160));
write(`${res}/drawable/splash_icon.xml`, vector(240, 160, circle160));
// Theme android:background on the launch window: colour + the centred circle
// icon; no bitmap, so no screen ratio can crop or shift it.
write(
  `${res}/drawable/splash.xml`,
  `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GENERATED} -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/plusone_shell_background" />
    <item
        android:width="160dp"
        android:height="160dp"
        android:gravity="center">
        <shape android:shape="oval">
            <solid android:color="@color/ic_launcher_background" />
        </shape>
    </item>
    <item
        android:width="240dp"
        android:height="240dp"
        android:drawable="@drawable/splash_mark"
        android:gravity="center" />
</layer-list>
`,
);

// Remove the retired bitmap sets (@capacitor/assets output + template defaults).
for (const dir of readdirSync(at(res))) {
  for (const f of ['splash.png', 'ic_launcher_foreground.png', 'ic_launcher_background.png']) {
    rmSync(at(res, dir, f), { force: true });
  }
}
rmSync(at(res, 'drawable-v24/ic_launcher_foreground.xml'), { force: true });
rmSync(at(res, 'drawable/ic_launcher_background.xml'), { force: true });
for (const dir of readdirSync(at(res))) {
  if (/^(drawable|mipmap)/.test(dir) && readdirSync(at(res, dir)).length === 0) rmSync(at(res, dir), { recursive: true });
}

// --- iOS ---------------------------------------------------------------------
const xc = 'ios/App/App/Assets.xcassets';
const appicon = `${xc}/AppIcon.appiconset`;
rmSync(at(appicon), { recursive: true, force: true });
const IOS_ICONS = [
  ['iphone', 20, 2], ['iphone', 20, 3], ['iphone', 29, 2], ['iphone', 29, 3],
  ['iphone', 40, 2], ['iphone', 40, 3], ['iphone', 60, 2], ['iphone', 60, 3],
  ['ipad', 20, 1], ['ipad', 20, 2], ['ipad', 29, 1], ['ipad', 29, 2],
  ['ipad', 40, 1], ['ipad', 40, 2], ['ipad', 76, 1], ['ipad', 76, 2], ['ipad', 83.5, 2],
  ['ios-marketing', 1024, 1],
];
const images = [];
for (const [idiom, pt, scale] of IOS_ICONS) {
  const px = Math.round(pt * scale);
  const filename = `AppIcon-${px}.png`;
  await png(`${appicon}/${filename}`, px, { tile: LAVENDER }, { opaque: true });
  images.push({ filename, idiom, scale: `${scale}x`, size: `${pt}x${pt}` });
}
write(`${appicon}/Contents.json`, `${JSON.stringify({ images, info: { author: 'xcode', version: 1 } }, null, 2)}\n`);

// Launch screen: the storyboard centres this 160pt circle on #0B0B0D.
const splashset = `${xc}/Splash.imageset`;
rmSync(at(splashset), { recursive: true, force: true });
const splashImages = [];
for (const scale of [1, 2, 3]) {
  const filename = `splash-icon@${scale}x.png`;
  await png(`${splashset}/${filename}`, 160 * scale, { tile: LAVENDER, circle: true });
  splashImages.push({ filename, idiom: 'universal', scale: `${scale}x` });
}
write(`${splashset}/Contents.json`, `${JSON.stringify({ images: splashImages, info: { author: 'xcode', version: 1 } }, null, 2)}\n`);

// --- PWA ---------------------------------------------------------------------
// Full-bleed tiles; at 36% glyph height the mark sits well inside the 80%
// maskable safe circle, so the same art serves "any" and "maskable".
for (const px of [192, 512]) {
  await png(`public/icon-${px}x${px}.png`, px, { tile: LAVENDER }, { opaque: true });
  await png(`public/icon-maskable-${px}x${px}.png`, px, { tile: LAVENDER }, { opaque: true });
}
await png('public/apple-touch-icon.png', 180, { tile: LAVENDER }, { opaque: true });

// --- Favicon -----------------------------------------------------------------
// The one exception to MARK_HEIGHT: at 16px a 36% glyph is ~6px of ink and the
// "1" turns to mush, so the tab icon uses a bigger mark on a rounded lavender
// tile. The tile is what keeps it visible on both light and dark tab strips
// (the #16132B ink alone vanishes on a dark strip).
const FAVICON = { tile: LAVENDER, radius: 0.22, height: 0.6 };
const FAVICON_SIZES = [16, 32, 48];
write(
  'src/app/icon.svg',
  svg(1024, FAVICON).replace('<svg ', `<!-- ${GENERATED} -->\n<svg `) + '\n',
);
const faviconPngs = await Promise.all(
  FAVICON_SIZES.map((px) =>
    sharp(Buffer.from(svg(1024, FAVICON)), { density: 72 }).resize(px, px).png({ compressionLevel: 9 }).toBuffer(),
  ),
);
// ICO container with PNG payloads (supported by every current browser):
// 6-byte ICONDIR, one 16-byte ICONDIRENTRY per size, then the PNG bytes.
const icoHeader = Buffer.alloc(6 + 16 * faviconPngs.length);
icoHeader.writeUInt16LE(0, 0); // reserved
icoHeader.writeUInt16LE(1, 2); // type: icon
icoHeader.writeUInt16LE(faviconPngs.length, 4);
let icoOffset = icoHeader.length;
faviconPngs.forEach((buf, i) => {
  const e = 6 + 16 * i;
  icoHeader.writeUInt8(FAVICON_SIZES[i] % 256, e); // width (0 = 256)
  icoHeader.writeUInt8(FAVICON_SIZES[i] % 256, e + 1); // height
  icoHeader.writeUInt8(0, e + 2); // palette colours
  icoHeader.writeUInt8(0, e + 3); // reserved
  icoHeader.writeUInt16LE(1, e + 4); // colour planes
  icoHeader.writeUInt16LE(32, e + 6); // bits per pixel
  icoHeader.writeUInt32LE(buf.length, e + 8);
  icoHeader.writeUInt32LE(icoOffset, e + 12);
  icoOffset += buf.length;
});
writeFileSync(at('src/app/favicon.ico'), Buffer.concat([icoHeader, ...faviconPngs]));

// Legibility preview: 16px and 32px, each next to a 64px nearest-neighbour zoom,
// on a light and a dark tab strip.
{
  const strips = [
    { bg: '#F1F3F4', y: 0 },
    { bg: '#202124', y: 96 },
  ];
  const layers = [];
  for (const { y } of strips) {
    let x = 24;
    for (const [i, px] of [16, 32].entries()) {
      const buf = faviconPngs[FAVICON_SIZES.indexOf(px)];
      layers.push({ input: buf, left: x, top: y + (96 - px) / 2 });
      x += px + 24;
      const zoom = await sharp(buf).resize(64, 64, { kernel: 'nearest' }).png().toBuffer();
      layers.push({ input: zoom, left: x, top: y + 16 });
      x += 64 + (i === 0 ? 40 : 24);
    }
  }
  const W = 24 + 16 + 24 + 64 + 40 + 32 + 24 + 64 + 24;
  const strip = (bg, y) => `<rect x="0" y="${y}" width="${W}" height="96" fill="${bg}"/>`;
  mkdirSync(at('docs/store/preview'), { recursive: true });
  await sharp(Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="192">${strips.map((t) => strip(t.bg, t.y)).join('')}</svg>`))
    .composite(layers)
    .png({ compressionLevel: 9 })
    .toFile(at('docs/store/preview/favicon-preview.png'));
}

console.log('native-icons: regenerated from native/icon/plusone-mark.svg');
